AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*

Documentation:
  Enabled: false

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/EmptyLines:
  Enabled: false
